### ISSUE TITLE
script to run for results in Table-1

### ISSUE THREAD

**Issue by krantiparida** [SheldonTsui/PseudoBinaural_CVPR2021#4]
Hi, Thanks for sharing the code. Could you please clarify which script to run for the results mentioned in Table-1? In the scripts folder, there are two types of scripts one with simple `audionet` and the other `APNet` backbone. As per the paper, for the separation task, `APNet` backbone is only used whereas for the stereo task `APNet` is not used. But I could not find a setting that satisfies this condition. Please clarify.

**Comment by SheldonTsui** [comment]
Hi, @krantiparida. Please notice that `APNet` is just an associate head for the separation task and `audionet` serves as the backbone. We used `audionet` for the stereo task and an extra `APNet` head for the separation. In order to fit this training mode, the 'train.py' script should be slightly modified. Accordingly, the checkpoints of the `audionet` backbone and the `APNet` head must be stored for the inference.

**Comment by krantiparida** [comment]
Thanks for the clarification.
